Initial checkin
Azure-Samples/live-video-analytics-iot-edge-csharp pull request #21
Opened 2020-09-10 14:54 UTC by gadamilan

http extension sample

2020-09-10 18:29 UTC, naiteeks commented on src/edge/deployment.httpExtension.template.json
> +                        "HostPort": "8554"
are we sure of the port number here?

2020-09-10 18:34 UTC, naiteeks commented on src/edge/deployment.httpExtension.template.json
> +              "image": "${MODULES.httpExtension}",
I am assuming the value for the image will be stored in the .env file. Since we do not populate this as a part of the setup script, should we have a note in the readme file for the user to add this?

2020-09-10 18:38 UTC, naiteeks commented on src/edge/modules/httpExtension/Program.cs
> +                //string msg = "{\"msg\" : \"Hello World\"}";
remove this comment ?

2020-09-10 18:39 UTC, naiteeks commented on src/edge/readme.md
> +In addition to the moduels defined in deployment.template.json, this deployment manifest template includes a sample httpExtension module (source code for which can be found in ./modules/httpExtension
In addition to the **modules**...

2020-09-10 18:52 UTC, naiteeks commented on src/cloud-to-device-console-app/operations.json
> +                "topologyUrl": "https://raw.githubusercontent.com/Azure/live-video-analytics/master/MediaGraph/topologies/httpExtension/topology.json"
This will change the default toplogy to httpExtension instead of motiondetection. Our docs have motiondetection as default. We can change the verbiage there if that is the direction we want to go.

2020-09-10 18:54 UTC, naiteeks requested changes
Just for attention, This will change the default topology to httpExtension instead of motiondetection. Our docs have motiondetection as default.

2020-09-12 19:30 UTC, rodrigb requested changes

2020-09-12 19:30 UTC, rodrigb commented on src/edge/modules/httpExtension/Program.cs
> +        class Worker
Why there is a need for a new class? Also, the class receives the http context. This is a bit strange.

2020-09-12 19:30 UTC, rodrigb commented on src/edge/modules/httpExtension/Program.cs
> +                new Thread(new Worker(ctx).ProcessRequest).Start();
Task should be preferred as creating a new thread has a much bigger overhead.

2020-09-12 19:30 UTC, rodrigb commented on src/edge/modules/httpExtension/Program.cs
> +                if (inference.Length > 0)
This is not a good practice. Code can be rearranged to avoid the empty initialization and this comparison

2020-09-12 19:30 UTC, rodrigb commented on src/edge/modules/httpExtension/Program.cs
> +                string inferenceString = "";
Initializing to empty string is not a good practice.

2020-09-12 19:30 UTC, rodrigb commented on src/edge/modules/httpExtension/Program.cs
> +                    inferenceString = inference.ToString();
You are supposed to return an array of inferences. It looks like this is returning a sing object.

https://docs.microsoft.com/en-us/azure/media-services/live-video-analytics-edge/http-extension-protocol

2020-09-12 19:30 UTC, rodrigb commented on src/edge/modules/httpExtension/Program.cs
> +                    classification.value = colorIntensity;
Looks like you are missing the tag object. Classification doesn't have a value property.

2020-09-12 19:30 UTC, rodrigb commented on src/edge/modules/httpExtension/Program.cs
> +using System;
Overall I think that we should have standard header doc with copyright and licensing for **ALL** samples files and proper documentation on samples.

2020-09-12 19:30 UTC, rodrigb commented on src/edge/modules/httpExtension/Program.cs
> +                //Check.NotNull(image, nameof(image));
Remove

2020-09-12 19:30 UTC, rodrigb commented on src/edge/modules/httpExtension/Program.cs
> +            private Bitmap ToGrayScale(Image source)
This method name is used for extensions, which  is not the case here. ConvertImageToGrayScale.

2020-09-12 19:30 UTC, rodrigb commented on src/edge/modules/httpExtension/Program.cs
> +                        var image = Image.FromStream(requestStream);
using ?

2020-09-12 19:30 UTC, rodrigb commented on src/edge/modules/httpExtension/Program.cs
> +            public void ProcessRequest()
Missing exception handling

2020-09-15 19:36 UTC, johndeu commented
Why is this PR still open?

2020-10-09 13:28 UTC, gadamilan commented on src/edge/deployment.httpExtension.template.json
> +              "image": "${MODULES.httpExtension}",
No, it won't be in the .env file. The value goes in module.json

2020-10-09 13:28 UTC, gadamilan commented on src/edge/modules/httpExtension/Program.cs
> +                //string msg = "{\"msg\" : \"Hello World\"}";
Yes, it needs to be removed

2020-10-09 13:28 UTC, gadamilan commented on src/edge/deployment.httpExtension.template.json
> +                        "HostPort": "8554"
That is the default in all our deployment manifests

2020-10-09 13:30 UTC, gadamilan commented on src/cloud-to-device-console-app/operations.json
> +                "topologyUrl": "https://raw.githubusercontent.com/Azure/live-video-analytics/master/MediaGraph/topologies/httpExtension/topology.json"
You are right. We need to remove changes to operation.json. I put it in the PR branch as I was testing it

2021-01-20 23:04 UTC, merged