Grpc extension
Azure-Samples/live-video-analytics-iot-edge-csharp pull request #26
Opened 2020-10-26 22:34 UTC by nicolasbotto

2020-10-26 23:40 UTC, ethanshea-ms requested changes

2020-10-26 23:40 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/Core/MemoryMappedFileMemoryManager.cs
> +            else
Same comment here about the else: there should be an explicit check for windows. (unless the code in the else block does work for every other platform)

2020-10-26 23:40 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/Core/MemoryMappedFileMemoryManager.cs
> +        {
nit: Include a comment about why this method can be blank. Ex:

"The manager accesses, but does not own resources. Therefore there is nothing to unpin."

2020-10-26 23:40 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/Dockerfile
> +#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
nit: Remove comment

2020-10-26 23:40 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/Models/Inference.cs
> +
nit: Spacing

2020-10-26 23:40 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/Processors/ImageProcessor.cs
> +    /// <summary>Class <c>ImageProcessor</c> is responsible for processing an <paramref name="image"/>.
nit: Since this is the summary to a class, the `paramref` does not actually reference anything. (I think 🙂)

2020-10-26 23:40 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/Processors/ImageProcessor.cs
> +            {
nit: Indentation

2020-10-26 23:40 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/Processors/ImageProcessor.cs
> +            byte[] imageBytes = GetBytes(grayScaleImage);
Since `GetBytes` returns the image bytes in a JPEG encoding, this function does not actually calculate light vs dark

2020-10-26 23:40 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/Services/MediaGraphExtensionService.cs
> +        private Memory<byte> _memory;
These variables exist per-session. Because of this, the service can only serve one client at a time

2020-10-26 23:40 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/Services/MediaGraphExtensionService.cs
> +                    case MediaStreamMessage.PayloadOneofCase.MediaStreamDescriptor:
nit: We can emphasize the fact that the media stream descriptor is sent first by assuming it is the first message sent.

The implementation might look something like this where the first message is received/validated/processed separately from the media samples.

https://github.com/Azure/live-video-analytics/blob/ea29662919f0116f74880430585f457204baa82a/utilities/video-analysis/notebooks/Yolo/yolov3/yolov3-grpc-icpu-onnx/lvaextension/server/inference_engine.py#L179-L194

2020-10-26 23:40 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/Models/InferenceResponse.cs
> +    public class InferenceResponse
What is the motivation for this class over an enumerable of inferences?

2020-10-26 23:40 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/Services/MediaGraphExtensionService.cs
> +                        mediaSampleResponse.Inferences.AddRange(ToMediaSampleInference(inferencesResponse));
This can be written:

```csharp
var mediaSampleResponse = new MediaSample()
{
  Inferences = { ToMediaSampleInference(inferencesResponse) },
}
```

2020-10-26 23:40 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/grpcExtension.csproj
> +  </PropertyGroup>
nit: These can be simplified into the above property group

2020-10-31 02:06 UTC, ethanshea-ms requested changes
This is looking better but there are two major issues which are blocking.
- Since fields in `MediaGraphExtensionService` like `_clientMediaDescriptor` or `_memoryManager` are scoped to the service rather than the call, this will not function correctly with multiple clients (which could be graph extension nodes in LVA)
- `ImageProcessor.GetBytes` returns JPEG encoded bytes, so the intensity calculation is running over compressed data and is not meaningful.

There's a couple previous comments which have not been addressed, so those may be worth taking a look as well but they are not blocking.

2020-10-31 02:06 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/Services/MediaGraphExtensionService.cs
> +                // If batch size hasn't been reached, return dummy response
nit: This isn't a dummy response, it is an acknowledgement of the frame which happens to contain no inferences.

2020-10-31 02:06 UTC, ethanshea-ms commented on src/edge/modules/grpcExtension/Services/MediaGraphExtensionService.cs
> +            var stream = new MemoryStream();
nit: I think there's a couple `MemoryStream` constructors which take a byte array, can that be used to avoid an extra copy?

2020-11-03 19:13 UTC, naiteeks commented on src/edge/modules/grpcExtension/Processors/BatchImageProcessor.cs
> +        public IEnumerable<Inference> ProcessImage(List<Image> images)
are we changing the function name here? @nicolasbotto -? If so, be sure to update the Readme page

2020-11-03 19:14 UTC, naiteeks commented on src/edge/modules/grpcExtension/Services/MediaGraphExtensionService.cs
> +                // If batch size hasn't been reached, return dummy response
@nicolasbotto -  fix comment

2020-11-03 19:15 UTC, naiteeks commented on src/edge/modules/grpcExtension/readme.md
> +IEnumerable<Inference> ProcessImage(List<Image> images)
if changing the file name, please update the entry here

2020-11-03 19:16 UTC, naiteeks reviewed
Lets review the comments

2020-11-03 19:20 UTC, nicolasbotto commented on src/edge/deployment.grpc.template.json
> +                                "IpcMode": "container:lvaEdge"
I've restarted several times the extension and didn't face any issue.

2020-11-03 19:52 UTC, nicolasbotto commented on src/edge/modules/grpcExtension/Processors/BatchImageProcessor.cs
> +        public IEnumerable<Inference> ProcessImage(List<Image> images)
Updated the readme page with new method name

2020-11-03 20:41 UTC, nicolasbotto commented on src/edge/modules/grpcExtension/Models/InferenceResponse.cs
> +    public class InferenceResponse
Using grpc contracts instead

2020-11-03 20:42 UTC, nicolasbotto commented on src/edge/modules/grpcExtension/Models/Inference.cs
> +
File has been removed.

2020-11-03 20:43 UTC, nicolasbotto commented on src/edge/modules/grpcExtension/Core/MemoryMappedFileMemoryManager.cs
> +        /// Initializes a new instance of the <see cref="MemoryMappedFileAccessor"/> class.
File has been removed

2020-11-03 23:05 UTC, ethanshea-ms approved these changes
This looks good, thanks for updating. The only issue remaining is that because the memory manager is shared across all sessions, the server can only handle one client using shared memory transfer at once. If you are not worried about this, the code can be merged.

2020-11-03 23:13 UTC, merged