Http extension
Azure-Samples/live-video-analytics-iot-edge-csharp pull request #27
Opened 2020-10-26 22:35 UTC by nicolasbotto

2020-10-26 23:49 UTC, ethanshea-ms requested changes
Make sure to incorporate comments in shared files from the below PR.

https://github.com/Azure-Samples/live-video-analytics-iot-edge-csharp/pull/26#pullrequestreview-517225701

2020-10-26 23:49 UTC, ethanshea-ms commented on src/edge/modules/httpExtension/Controllers/ScoreController.cs
> +namespace httpExtension.Controllers
Namespace should be capitalized to follow C# convention

2020-10-26 23:49 UTC, ethanshea-ms commented on src/edge/modules/httpExtension/Readme.md
> +* Our local Docker container image is already loged into ACR.
Should this read "Our local docker context is logged into our ACR"?

2020-10-26 23:49 UTC, ethanshea-ms commented on src/edge/modules/httpExtension/Readme.md
> +	"@apiVersion": "1.0",
nit: Indentation

I think this mixes tabs and spaces

2020-10-26 23:49 UTC, ethanshea-ms commented on src/edge/modules/httpExtension/Readme.md
> +            "encoding": "jpeg",
Using this, the images will be transferred with the JPEG encoding, but in the description at the top of the file, it says that decoded images are transferred.

2020-10-26 23:49 UTC, ethanshea-ms commented on src/edge/modules/httpExtension/Readme.md
> +> If you're unfamiliar with ACR or have any questions, please follow this [demo on building and pushing an image into ACR](https://docs.microsoft.com/en-us/azure/container-registry/container-registry
These lines are duplicated, is this intentional?

2020-12-02 20:29 UTC, nicolasbotto commented
@ethanshea-ms I've addressed your comments, please review them. Thanks

2020-12-10 18:14 UTC, naiteeks commented
@ethanshea-ms  - good to merge?

2020-12-11 21:03 UTC, naiteeks commented
@gadamilan  - for review.

2020-12-11 23:23 UTC, merged