Intel grpc dl streamer module
Azure-Samples/live-video-analytics-iot-edge-csharp pull request #45
Opened 2021-02-18 12:32 UTC by fvneerden

Files used in the new Intel OpenVINO DL Streamer - Edge AI Extension tutorial

2021-02-18 16:39 UTC, anilmur commented on src/edge/readme.md
> +In addition to the modules defined in deployment.template.json, this deployment manifest template includes the [OpenVINO™ DL Streamer – Edge AI Extension Module](https://aka.ms/lva-intel-openvino-dl-
Instead of https://aka.ms/lva-intel-openvino-dl-streamer-tutorial 

use https://aka.ms/lva-intel-grpc  

After your tutorial ships, the above will be redirected...

2021-02-18 16:40 UTC, anilmur commented on src/edge/readme.md
> +This template is the same as defined in deployment.openvino.grpc.cpu.template.json, but here the GPU support is enabled so that the inferencing will use the GPU. This deployment manifest template inc
Instead of https://aka.ms/lva-intel-openvino-dl-streamer-tutorial

use https://aka.ms/lva-intel-grpc

2021-02-18 16:40 UTC, anilmur requested changes
Please use https://aka.ms/lva-intel-grpc

2021-02-22 08:32 UTC, fvneerden commented on src/edge/readme.md
> +In addition to the modules defined in deployment.template.json, this deployment manifest template includes the [OpenVINO™ DL Streamer – Edge AI Extension Module](https://aka.ms/lva-intel-openvino-dl-
Changed to https://aka.ms/lva-intel-grpc

2021-02-22 08:32 UTC, fvneerden commented on src/edge/readme.md
> +This template is the same as defined in deployment.openvino.grpc.cpu.template.json, but here the GPU support is enabled so that the inferencing will use the GPU. This deployment manifest template inc
Changed to https://aka.ms/lva-intel-grpc

2021-02-22 08:34 UTC, closed without merging